=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno17.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sales">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="salesman">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="middle" type="xs:string"/>
                    <xs:element name="last" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="title" type="xs:string"/>
                </xs:complexType>              
              </xs:element>
              <xs:element name="phone" type="phoneType"/>
              <xs:element name="area" type="xs:string"/>
              <xs:element name="records">
                <xs:complexType >
                  <xs:sequence>
                    <xs:element name="record" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence >
                          <xs:element name="product">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="sku" type="xs:integer"/>
                                <xs:element name="product_name" type="xs:string"/>                              
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:integer"/>                            
                            </xs:complexType>                          
                          </xs:element>
                          <xs:element name="quantity" type="xs:string"/>
                          <xs:element name="price">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:integer">
                                  <xs:attribute name="currency">
                                    <xs:simpleType>
                                      <xs:restriction base="xs:string">
                                        <xs:enumeration value="npr"/>
                                        <xs:enumeration value="inr"/>
                                        <xs:enumeration value="usd"/>                                  
                                      </xs:restriction>                                
                                    </xs:simpleType>                              
                                  </xs:attribute>
                                  </xs:extension>
                                 </xs:simpleContent>                            
                              </xs:complexType>                          
                            </xs:element>
                          <xs:element name="date" type="dateType"/>                        
                        </xs:sequence>                     
                      </xs:complexType>                    
                    </xs:element>                  
                  </xs:sequence>
                </xs:complexType>             
              </xs:element>            
            </xs:sequence>          
          </xs:complexType>        
        </xs:element>      
      </xs:sequence>    
    </xs:complexType>
  </xs:element>
  <xs:complexType name="phoneType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="type">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="personal"/>
              <xs:enumeration value="work"/>
              <xs:enumeration value="home"/>            
            </xs:restriction>          
          </xs:simpleType>        
        </xs:attribute>      
      </xs:extension>    
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="dateType">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attribute name="type">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="ad"/>
              <xs:enumeration value="bs"/>        
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno17.xml
<?xml version="1.0" encoding="UTF-8"?>
<sales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="qsnno17.xsd">
  <salesman>
    <name title="pb">
      <first>prajwal</first>
      <middle></middle>
      <last>bhattarai</last>
    </name>
    <phone type="personal">9812345678</phone> 
    <area>patandhoka</area>
    <records>
      <record>
        <product id="1547">
          <sku>17865</sku>
          <product_name>Acer nitro 5</product_name>
        </product>
        <quantity>5</quantity>
        <price currency="inr">250000</price>
        <date type="ad">2022</date>
      </record>
       <record>
        <product id="5558">
          <sku>6584</sku>
          <product_name>Hp Pavilion 15</product_name>
        </product>
        <quantity>10</quantity>
        <price currency="npr">1000000</price>
        <date type="bs">2080</date>
      </record>    
    </records>
  </salesman>
</sales>
