=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno13.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="hospital">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="patient">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="middle" type="xs:string"/>
                    <xs:element name="last" type="xs:string"/>                  
                  </xs:sequence>                
                </xs:complexType>              
              </xs:element>
              <xs:element name="number">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9]{5}"/>                  
                  </xs:restriction>                
                </xs:simpleType>              
              </xs:element>
              <xs:element name="doctorname" type="xs:string"/>
              <xs:element name="diseases">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="disease" type="xs:string" maxOccurs="unbounded"/>                  
                  </xs:sequence>                
                </xs:complexType>              
              </xs:element>
              <xs:element name="consultation_charge">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="500"/>
                    <xs:maxInclusive value="5000"/>                  
                  </xs:restriction>                
                </xs:simpleType>              
              </xs:element>
              <xs:element name="lab_tests">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="lab_test" type="xs:string" maxOccurs="unbounded"/>                  
                  </xs:sequence>                
                </xs:complexType>              
              </xs:element>            
            </xs:sequence>          
          </xs:complexType>        
        </xs:element>      
      </xs:sequence>    
    </xs:complexType>
  </xs:element>
</xs:schema>

=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno13.xml
<?xml version="1.0" encoding="UTF-8"?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="qsnno13.xsd">
  <patient>
    <name>
      <first>Ram</first>
      <middle>Bahadur</middle>
      <last>Gurung</last>    
    </name>
    <number>12345</number>
    <doctorname>Krishna Shakya</doctorname>
    <diseases>
      <disease>Gastric</disease>
      <disease>Sugar</disease>
    </diseases>
    <consultation_charge>4500</consultation_charge>
    <lab_tests>
      <lab_test>Blood Test</lab_test>
      <lab_test>Thyroid Test</lab_test>
    </lab_tests>
  </patient>
</hospital>
