=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="books">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="authors">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="author" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="first_name" type="xs:string"/>
                                <xs:element name="middle_name" type="xs:string"/>
                                <xs:element name="last_name" type="xs:string"/>
                              </xs:sequence>                            
                            </xs:complexType>                          
                          </xs:element>
                          <xs:element name="phone" type="xs:string"/>
                          <xs:element name="email" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="author_title" type="AuthorTitleType"/>
                      </xs:complexType>  
                    </xs:element>                  
                  </xs:sequence>                
                </xs:complexType>
              </xs:element>
              <xs:element name="page_no" type="xs:integer"/>
              <xs:element name="price">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="PriceType">
                      <xs:attribute name="currency" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="NPR"/>
                            <xs:enumeration value="INR"/>
                            <xs:enumeration value="USD"/>
                          </xs:restriction>                        
                        </xs:simpleType>  
                        </xs:attribute>
                        </xs:extension>                  
                  </xs:simpleContent>                
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ISBN" type="xs:string"/>             
          </xs:complexType>        
        </xs:element>      
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    <xs:simpleType name="AuthorTitleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="mrs"/>
      <xs:enumeration value="ms"/>
      <xs:enumeration value="mr"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PriceType">
    <xs:restriction base="xs:decimal">
      <xs:maxInclusive value="600"/>
    </xs:restriction>
  </xs:simpleType>
  </xs:schema>

=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno4.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="qsnno4.xsd">
  <book ISBN="123-698">
    <title>Web Technology</title>
    <authors>
      <author author_title="mr">
        <name>
          <first_name>Basanta</first_name>
          <middle_name></middle_name>
          <last_name>Chapagain</last_name>
        </name>
        <phone>9812345678</phone>
        <email>chapagainbasanta1@gmail.com</email>
      </author>
    </authors>
    <page_no>300</page_no>
    <price currency="NPR">500</price>
  </book>
  <book ISBN="5648-658">
    <title>System Analysis and Design</title>
    <authors>
      <author author_title="ms">
        <name>
          <first_name>Sunita</first_name>
          <middle_name>Kumari</middle_name>
          <last_name>Magar</last_name>
        </name>
        <phone>9864521578</phone>
        <email>sunitaofficial15@gmail.com</email>
      </author>
    </authors>
    <page_no>350</page_no>
    <price currency="INR">600</price>
  </book>
</books>
