=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="movies">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="movie" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="year" type="xs:integer"/>
              <xs:element name="_director" type="directorType"/>
              <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="comment">  
                  <xs:complexType>
                    <xs:attribute name="lang" type="xs:string"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="newcomment" type="xs:string"/>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer"/>
          </xs:complexType>        
        </xs:element>      
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="directorType">
   <xs:simpleContent>
    <xs:extension base="xs:string">
      <xs:attribute name="name" type="xs:string"/>
    </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno7.xml
<?xml version="1.0" encoding="UTF-8"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="qsnno7.xsd">
  <movie id="1">
    <title>Pashupati Prasad</title>
    <year>2020</year>
    <_director name="Dipendra K. Khanal">Dipendra K .Khanal</_director>
    <comment lang="english"></comment>
    <newcomment></newcomment>
  </movie>
  <movie id="2">
    <title>Jatrai Jatra</title>
    <year>2021</year>
    <_director name="Pradip Bhattarai">Pradip Bhattarai</_director>
    <comment lang="english"></comment>
    <newcomment></newcomment>
  </movie>
</movies>
