=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xsd:element name="school">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="name" type="xsd:string"/>
        <xsd:element name="locations">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="location" type="xsd:string" maxOccurs="unbounded"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="staffs">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="staff" type="staffType" maxOccurs="unbounded"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="subjects">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="subject" type="subjectType" maxOccurs="unbounded"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="staffType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="title" type="xsd:string" minOccurs="0"/>
      <xsd:element name="category">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="academic"/>
            <xsd:enumeration value="general"/>
            <xsd:enumeration value="technical"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="address" type="addressType" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="addressType">
    <xsd:sequence>
      <xsd:element name="street" type="xsd:string"/>
      <xsd:element name="suburb" type="xsd:string"/>
      <xsd:element name="postcode" type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="subjectType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="description" type="xsd:string"/>
      <xsd:element name="capacity">
        <xsd:simpleType>
          <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="6"/>
            <xsd:maxInclusive value="400"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="Staff-Ref" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="id" type="xsd:IDREF" use="required"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
  </xsd:complexType>

</xsd:schema>

=== oliAjita/Web-Technology-Third-Sem-Lab-2-XML-/qsnno6.xml
<?xml version="1.0" encoding="UTF-8"?>
<school id="s123" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="qsnno6.xsd">
  <name>Shree Janajyoti Madhyamik Bidyamandir</name>
  <locations>
    <location>Balkumari, Lalitpur</location>  
    <location>PatanDhoka, Lalitpur</location>
  </locations>
  <staffs>
    <staff id="st456">
      <name>Ramesh Singh Saud</name>
      <title>Mr</title>
      <category>academic</category>
      <address>
        <street>Krishna Galli, 3rd Street, Patan</street>
        <suburb>PatanDhoka</suburb>
        <postcode>44600</postcode>
      </address>
    </staff>
    <staff id="st789">
      <name>Krishna Chapagain</name>
      <title>Mr</title>  
      <category>technical</category>
      <address>
        <street>Newroad, 4th Street, Kathmandu</street>    
        <suburb>Pipalbot</suburb>
        <postcode>44600</postcode>
      </address>
    </staff>
  </staffs>
  <subjects>
    <subject id="sub111">
      <name>Web Technology</name>
      <description>This subject is related to web development.</description>    
      <capacity>7</capacity>  
      <Staff-Ref id="st456"/>
      <Staff-Ref id="st789"/>
    </subject> 
    <subject id="sub222">
      <name>Data Structures and Algorithms</name>
      <description>This subject is related to techniques of storing data and writing their algorithms.</description>    
      <capacity>400</capacity>
      <Staff-Ref id="st456"/>
    </subject>
  </subjects>
</school>
